""""Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."""


n = int(input().strip()) # n = 4*(10**6)
a = 1
b = 2
c = a + b
evensum = 2
while c <= n:
    a, b = b, c
    c = a + b
    if b % 2 == 0:
        evensum = evensum + b
print(evensum)

# Answer = 4613732
